services:
  java-service-sample-1:
    container_name: java-1
    build:
      context: sample1/
    tty: true
    volumes:
      - ./sample1:/home/vscode/workspace/sample1:cached
    ports:
      - 8080:8080

  java-service-sample-2:
    container_name: java-2
    build:
      context: sample2/
    tty: true
    volumes:
      - ./sample2:/home/vscode/workspace/sample2:cached
    ports:
      - 8081:8081
